import Head from 'next/head'

const Home = () => {
   return (
      <>
         <Head>
            <title>Charity Assistant</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <div>Не удалось подключиться к серверу</div>
      </>
   )
}

export default Home
